spring:
  datasource:
    url: jdbc:mysql://root:fKqMAxyowRaAcNJnHwhmRuGtnctfRGWG@shortline.proxy.rlwy.net:46345/railway
    username: root
    password: fKqMAxyowRaAcNJnHwhmRuGtnctfRGWG
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # ?? ?? ?? ??
      max-request-size: 50MB # ?? ?? ?? ??
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

# GPT 설정
openai:
  api:
    key: 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
    url: https://api.openai.com/v1/images/generations
jwt:
  secret: asfegefdwe14234trgw3c254

aws:
  s3:
    bucket: ecopedia-r
    region: ap-northeast-2 # 서울

s3-access-key: AKIAXEVXYVL2CJ6PSV4I
s3-secret-key: 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