spring:
  datasource:
    url: jdbc:mysql://root:fKqMAxyowRaAcNJnHwhmRuGtnctfRGWG@shortline.proxy.rlwy.net:46345/railway
    username: root
    password: fKqMAxyowRaAcNJnHwhmRuGtnctfRGWG
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # ?? ?? ?? ??
      max-request-size: 50MB # ?? ?? ?? ??
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

jwt:
  secret: asfegefdwe14234trgw3c254

aws:
  s3:
    bucket: ecopedia-r
    region: ap-northeast-2 # 서울

s3-access-key: AKIAXEVXYVL2CJ6PSV4I
s3-secret-key: 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